# first class nowadays: http://docs.travis-ci.com/user/languages/csharp/
language: csharp

mono:
 - beta
 - latest
 - 4.0.0
 - 3.12.0

solution: Hopac.sln

notifications:
  email: true

env:
  global:
    - EnableNuGetPackageRestore=true

script:
  - ./build.sh
