# first class nowadays: http://docs.travis-ci.com/user/languages/csharp/
language: csharp

sudo: false

mono:
 - beta
 - latest
 - 4.0.0
 - 3.12.0

solution: Hopac.sln

notifications:
  email: false # Sorry, travis ci builds fail with timeouts too often

env:
  global:
    - EnableNuGetPackageRestore=false

script:
  - ./build.sh
