# first class nowadays: http://docs.travis-ci.com/user/languages/csharp/
language: csharp

sudo: false

mono:
 - alpha
 - beta
 - latest
 - 4.0.0
 - 3.12.0

solution: Hopac.sln

notifications:
  email: false # Sorry, travis ci builds fail with timeouts too often

install:
 - mono --debug paket.bootstrapper.exe
 - mono --debug paket.exe install

script:
  - mono --debug packages/FAKE/tools/FAKE.exe build.fsx
  - xbuild Hopac.sln
  - mono --debug Benchmarks/PingPong/bin/Debug/PingPong.exe
